Add event index
m1chaell0/scheduler pull request #36
Opened 2021-06-23 11:40 UTC by m1chaell0

2021-06-28 12:45 UTC, unrooty requested changes

2021-06-28 12:45 UTC, unrooty commented on app/views/events/index.html.erb
> +
?

2021-06-28 12:45 UTC, unrooty commented on app/controllers/events_controller.rb
> +    @events = Event.all
do you really need to show user all events? :)

2021-06-28 12:45 UTC, unrooty commented on spec/requests/events/index_spec.rb
> +end
WTF? Did you check this spec?

2021-06-28 14:38 UTC, m1chaell0 commented on app/controllers/events_controller.rb
> +    @events = Event.all
yes, until I add pagination

2021-06-28 14:49 UTC, unrooty requested changes

2021-06-28 14:49 UTC, unrooty commented on app/controllers/events_controller.rb
> +    @events = Event.all
But does it make sense? You show all events to current users instead of the show only current_user's events to current_user.

2021-06-29 13:03 UTC, unrooty requested changes

2021-06-29 13:03 UTC, unrooty commented on spec/requests/events/index_spec.rb
> +end
And don't you need to check that only current user events shown?

2021-07-02 06:17 UTC, unrooty requested changes
Please add `.idea` folder to gitignore and remove this files from PR

2021-07-02 06:17 UTC, unrooty commented on app/models/category.rb
> +  has_many :events, dependent: :destroy
Please ALWAYS place those things in normal order. It helps to identify everything at the first look. F.e.
```suggestion
  has_many :events, dependent: :destroy

  belongs_to :user, optional: true

  validates :name, presence: true, uniqueness: true
```

2021-07-02 06:17 UTC, unrooty commented on app/views/events/index.html.erb
> +    </tbody>
Indent?

2021-07-02 08:36 UTC, closed without merging